### ISSUE TITLE
改完配置，main方法启动（springboot）还是报错

### ISSUE THREAD

**Issue by RobinsChens** [roncoo/roncoo-mybatis-generator#1]
![image](https://cloud.githubusercontent.com/assets/11987492/21175320/a01ab776-c21c-11e6-9155-bc3c588a4b55.png)

**Comment by fengyws** [comment]
出现了空指针异常，是不是路径配置错了呢

**Comment by freprite** [comment]
pom文件加上这个就可以了
`<resources>
			<resource>
				<directory>src/main/java</directory>
				<filtering>true</filtering>
				<includes>
					<include>**/*.xml</include>
					<include>**/*.properties</include>
					<include>**/*.dtd</include>
				</includes>
			</resource>
		</resources>`

**Comment by freprite** [comment]
pom文件加上这个就可以了
`<resources>
			<resource>
				<directory>src/main/java</directory>
				<filtering>true</filtering>
				<includes>
					<include>**/*.xml</include>
					<include>**/*.properties</include>
					<include>**/*.dtd</include>
				</includes>
			</resource>
		</resources>`

**Comment by jipengkun** [comment]
解决了，希望作者把这个配置加上去
